/**
 * Generate `lib/server/presentations/brand/embedded.ts`: the logo and a handful of gradient
 * scrims as base64 constants.
 *
 *   node scripts/presentations/embed-assets.mjs
 *
 * Why embed rather than read from `public/` at request time: the compile route runs as a
 * serverless function, and a file read there depends on output tracing having noticed the
 * file. A constant cannot go missing. Why generate the gradients here rather than at run
 * time: PptxGenJS has no gradient fills, so a readable-text scrim over a photo has to be a
 * transparent PNG layer — and drawing it once with the canvas devDependency is simpler than
 * hand-writing a PNG encoder in the route.
 *
 * A white logo variant is embedded only when a hand-made `public/logotxm-white.png` exists.
 * Deriving one from the colour logo's alpha channel was tried and produces a solid silhouette
 * (the artwork has no transparency inside its diamond), so on dark slides the colour logo
 * sits on a white pill instead.
 */

import { createCanvas, loadImage } from '@napi-rs/canvas';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const out = join(root, 'lib', 'server', 'presentations', 'brand', 'embedded.ts');

const INK = [0x14, 0x31, 0x3f];

function gradientPng(direction, maxAlpha = 0.88) {
  // A 1-pixel-thin strip stretched by the slide: 4 px across, 512 px along the gradient.
  const along = 512;
  const horizontal = direction === 'left' || direction === 'right';
  const canvas = createCanvas(horizontal ? along : 4, horizontal ? 4 : along);
  const ctx = canvas.getContext('2d');
  const grad = horizontal
    ? ctx.createLinearGradient(0, 0, along, 0)
    : ctx.createLinearGradient(0, 0, 0, along);
  // Ease-in so the transparent end fades out gently instead of showing a hard start line.
  const stops = 12;
  for (let i = 0; i <= stops; i++) {
    const t = i / stops;
    const eased = t * t * (3 - 2 * t);
    const a = (direction === 'up' || direction === 'left' ? 1 - eased : eased) * maxAlpha;
    grad.addColorStop(t, `rgba(${INK[0]},${INK[1]},${INK[2]},${a.toFixed(3)})`);
  }
  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  return canvas.toBuffer('image/png').toString('base64');
}

function logoVariants() {
  const colour = readFileSync(join(root, 'public', 'logotxm.png'));
  const whitePath = join(root, 'public', 'logotxm-white.png');
  const white = existsSync(whitePath) ? readFileSync(whitePath).toString('base64') : null;
  return { colour: colour.toString('base64'), white };
}

const logo = logoVariants();
const dims = await (async () => {
  const img = await loadImage(Buffer.from(logo.colour, 'base64'));
  return { width: img.width, height: img.height };
})();

const lines = [
  '/* Generated by scripts/presentations/embed-assets.mjs — do not edit by hand. */',
  '',
  `export const LOGO_PNG = '${logo.colour}';`,
  `export const LOGO_WHITE_PNG: string | null = ${logo.white ? `'${logo.white}'` : 'null'};`,
  `export const LOGO_ASPECT = ${(dims.width / dims.height).toFixed(4)};`,
  '',
  '/** Ink-coloured scrims, transparent at one end. Keyed by the direction the shadow deepens. */',
  'export const GRADIENTS = {',
  `  down: '${gradientPng('down')}',`,
  `  up: '${gradientPng('up')}',`,
  `  left: '${gradientPng('left')}',`,
  `  right: '${gradientPng('right')}',`,
  '} as const;',
  '',
];

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join('\n'));
console.log(
  `wrote ${out} (logo ${dims.width}x${dims.height}, white variant: ${logo.white ? 'from file' : 'none'})`,
);
